name: ci-build
on: [push, pull_request]

env:
  WASM_PACK_VERSION: 0.12.1

jobs:
  do-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo check --package ulid-cli
      - run: cargo test
      - run: cargo test --all-features
      - run: cargo test --no-default-features --features=std
      - run: cargo test --no-default-features

      - name: Create a directory for binary dependencies
        shell: bash
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Install wasm-pack
        working-directory: ${{ github.workspace }}/bin
        shell: bash
        run: |
          file_name="wasm-pack-v${WASM_PACK_VERSION}-x86_64-unknown-linux-musl"
          curl \
            --config ${GITHUB_WORKSPACE}/.github/curl_options \
            https://github.com/rustwasm/wasm-pack/releases/download/v${WASM_PACK_VERSION}/${file_name}.tar.gz \
            | tar --strip-components=1 -xzvf- "${file_name}/wasm-pack"

      - run: wasm-pack test --node --features js
